### ISSUE TITLE
use a webcam from an enketo-express form

### ISSUE THREAD

**Issue by AlexisTor** [kobotoolbox/enketo-express#1103]
Hello,
every form i create in a ODK aggregate with a photo field which is perfectly rendered and operrable by odk collect or kobo collect inside a mobile. but if i open with a browser rendered by kobotoolbox displays a field that show me an "select file dialog"

is there any way to use a webcam to take a photo directly to the browser?

thanks

**Comment by MartijnR** [comment]
Hi Alexis,

Support for the new appearances ('new-front', 'new-rear') has been added to Enketo. 

However, this is something that only (modern) **mobile** browsers have enabled for some reason. I think it's only a matter of time for this to become available on desktop browsers since the lines between desktop and mobile are becoming less defined. Not sure e.g. what happens on a Microsoft Surface tablet or Chrome OS device.
