### ISSUE TITLE
Boolean values evaluated as strings instead of booleans

### ISSUE THREAD

**Issue by NilsEnevoldsen** [kobotoolbox/enketo-express#193]
Enketo behaves differently from ODK Collect with regard to evaluating boolean expressions. Specifically, it appears to think that the false boolean value is the string "false", etc.

Take the following survey:

| type      | name        | label                        | calculation    |
|-----------|-------------|------------------------------|----------------|
| calculate | f           |                              | false()        |
| note      | dispf       | f: ${f}                      |                |
| calculate | fisfalse    |                              | ${f} = false() |
| note      | test1       | f is false: ${fisfalse}      |                |
| calculate | fistrue     |                              | ${f} = true()  |
| note      | test2       | f is true: ${fistrue}        |                |
| calculate | fiszero     |                              | ${f} = 0       |
| note      | test3       | f is zero: ${fiszero}        |                |
| calculate | fisstrfalse |                              | ${f} = "false" |
| note      | test5       | f is "false": ${fisstrfalse} |                |

Here are the results:

| Test         | Enketo | ODK Collect |
|--------------|--------|-------------|
| f            | false  | false       |
| f is false   | false  | true        |
| f is true    | true   | false       |
| f is zero    | false  | true        |
| f is "false" | true   | false       |

**Comment by MartijnR** [comment]
Thanks for this nice issue report. I wasn't aware of these differences and it makes me sad.

At first glance it seems to me that Enketo is correct here. Because a calculated item in XLSForm gets the string type and hence the value of ${f} is `"false"`.

I will play around with this!

**Comment by MartijnR** [comment]
http://www.w3.org/TR/xpath/#function-string

**Comment by NilsEnevoldsen** [comment]
Elegant workarounds that behave the same on both platforms are welcome in the meantime.

**Comment by MartijnR** [comment]
Yes, definitely. I understand.

There are limits to the amount of serious errors I can deliberately introduce to Enketo though, if I don't want this project to eventually kill itself due to increasing technical debt (for this I would have to change native XPath behaviour which actually isn't possible). In this case, knowing about the ODK issue, the best workaround might be best to compare strings instead. So wrap ${f} in string() when you compare even though it shouldn't be necessary.

cc @mitchellsundt, @ctsims if you have any insights, please let us know

**Comment by MartijnR** [comment]
I am not even sure that the behaviour should be different if type of ${f} is boolean actually because it would still be stored as 'false' in the XML instance (the behaviour for type='boolean' is the same in Enketo).

**Comment by ctsims** [comment]
Martijn

Here's my understanding of the situation:

In terms of XSD, the XSD schema states that Booleans my be represented as any of "0, 1, false, true" (with 0 and 1 being false and true respectively), so an incoming document with an "xsd:boolean" field should accept any of those inputs appropriately, I think.

XPath, however, has a different set of behaviors (because XPath walks a lonely road and throws rocks behind itself to discourage you from following):

Our XPath outputs for these inputs are:
string(2 = 3) -> "false"
string(3 = 3) -> "true"
string(false()) -> "false"
string(true()) -> "true"

boolean("true") -> true
boolean("false") -> true   (this is correct behavior)
boolean(0) -> false
boolean("") -> false

boolean("0") -> true

Which seems to align with the truth tables expected by
http://www.w3.org/TR/xpath/#function-boolean
http://www.w3.org/TR/xpath/#function-string

This is a minefield of painful behavior overall, because the XPath coercions themselves are notably inconsistent. For example:

boolean(string(boolean(expression))) = true() no matter what 

I believe our behavior is spec compliant, but to be honest with you we essentially hide all boolean datatypes in our product because their semantics are sufficiently unintuitive for our users as to be actively harmful. We encourage users to follow patterns like: Instead of storing a calculation as "/data/path/to/node = 'malaria'", they store it as "if(/data/path/to/node = 'malaria', 'yes', 'no')"

Which seems slightly cumbersome, but results in less errors.

**Comment by NilsEnevoldsen** [comment]
> So wrap ${f} in string() when you compare even though it shouldn't be necessary.

I am using this now, and it works fine. Thanks.

**Comment by MartijnR** [comment]
Thanks a lot Clayton. That's very helpful information.

>because XPath walks a lonely road and throws rocks behind itself to discourage you from following

:smile:

>I am using this now, and it works fine. Thanks.

Great. Let's just forget about this weirdness ;).

**Comment by NilsEnevoldsen** [comment]
Huh. I'm not sure I want to forget about it. Just because we have a workaround doesn't mean there's not an issue. The bottom line is that Enketo follows the spec, but ODK Collect doesn't? Then I should file an issue with ODK Collect.

I don't have enough expertise to be useful, but I've opened https://code.google.com/p/opendatakit/issues/detail?id=1135.

**Comment by MartijnR** [comment]
That's great. It seems that even if the spec if followed, it is not recommended to try to store boolean results of calculations due to XPath's quirkyness but instead do something like:

> Instead of storing a calculation as "/data/path/to/node = 'malaria'", ... store it as "if(/data/path/to/node = 'malaria', 'yes', 'no')"

**Comment by NilsEnevoldsen** [comment]
Right. Speaking of which, maybe https://opendatakit.org/help/form-design/binding/ etc should include that caveat.
