### ISSUE TITLE
Inconsistent handling of bad datatypes

### ISSUE THREAD

**Issue by jbonica** [kobotoolbox/enketo-express#206]
I believe there is some inconsistent error handling for invalid data type entry. 

When a user enters a STRING in a textfield calling for an INT datatype:

The invalid data is cleared from the field when focus is changed to another item. However, if the user clicks submit as his next action, the form is successfully submitted.

When a user enters a REAL in a textfield calling for an INT datatype:
The item is highlighted with a red box plus a message: "Value Not Allowed" and the user cannot Submit  or move to another Page. This seems like it should be the standard behavior.

When a user enters a STRING in a textfield calling for a REAL datatype:

The invalid data is cleared from the field when focus is changed to another item. However, if the user clicks submit as his next action, the form is successfully submitted.

Thanks!

**Comment by MartijnR** [comment]
Thanks. If the string value for an INT field is actually submitted to the server, we'll have to find a workaround. 

Otherwise, it might not be a sensible thing to work around, as we would have to work around native browser behaviour (detecting keypresses.. yuck). I suspect it's the latter (the value is cleared by the browser as soon as the submit button gets focus and the input button looses focus). (I can't test at the moment due to some serious internet constraints).

**Comment by MartijnR** [comment]
I think we have made this consistent with a mask on number inputs
