### ISSUE TITLE
Change background of repeats in Grid Theme

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#214]
Bright pink was suggested. Also `background: #efefef;`

**Comment by MartijnR** [comment]
also fix button location

<img width="1134" alt="screen shot 2015-07-31 at 10 42 43 am" src="https://cloud.githubusercontent.com/assets/627350/9012302/f2bc8064-3770-11e5-9212-50b33dd020bc.png">

**Comment by MartijnR** [comment]
<img width="1179" alt="screen shot 2015-07-31 at 2 34 13 pm" src="https://cloud.githubusercontent.com/assets/627350/9016823/470793be-3791-11e5-859e-ba285498cfcc.png">

**Comment by ccollins0601** [comment]
Looks very nice!

@MartijnR, have you ever given thought to doing a version of this layout where the question+hint text just appears as the column header rather than repeats within each row? More like a table or spreadsheet look & feel.

Is this possible now? If not I'll submit a separate feature request as OpenClinica would be interested in it, although it's not a real high priority for us just yet.

Best,
Cal

**Comment by MartijnR** [comment]
That's a cool idea. It's not possible currently. 

The issue would be that on small screens (or when switching from landscape to portrait) each question will get its own row. Not sure how to best work around that. Maybe it should revert back to the current style when the breakpoint (600px currently) is reached. That would seem implementable. Form designers would need to ensure that all repeat fields fit on one row.

Interesting...
