### ISSUE TITLE
Form not using fullscreen in portrait view in Android and iPhone

### ISSUE THREAD

**Issue by jbonica** [kobotoolbox/enketo-express#218]
Hey there,

This was just brought to my attention by a colleague on his iPhone and I was able to reproduce it on my Android. When a form is in portrait view, it is not filling the length of the screen. Please see attached screenshot. Resizing/responsiveness is working well in desktop Chrome and Firefox but has been observed in mobile Firefox and mobile Chrome.
![screenshot_2015-06-05-08-23-22](https://cloud.githubusercontent.com/assets/8268232/8006014/c461f79c-0b5d-11e5-8632-8df6ef877cb4.png)

**Comment by MartijnR** [comment]
Thanks! I thought that was fixed long time ago. I can't reproduce with http://enk.to/::widgets, so it might be something particular to your form.

If you can send the XForm, I can check quickly. If I can't reproduce it with your form, it is caused by the fact that enketo-express-oc hasn't been updated for a while.

**Comment by MartijnR** [comment]
reopen, with form if still exists
