### ISSUE TITLE
Minor: Markdown in notes not working. 

### ISSUE THREAD

**Issue by piqoni** [kobotoolbox/enketo-express#222]
Around 60 commits ago, markdown worked in notes.  ** bold ** would show **bold**, but in the latest version it doesn't. 
Something broke or was it intentional?

**Comment by MartijnR** [comment]
Thanks. Cannot reproduce. Please reopen this issue if you can reproduce it
on http://opendatakit.org/xiframe/ (the preview uses the latest Enketo
Express master).

Also see https://odk.enke.to/_/#YYYC (offline-capable) and
https://odk.enke.to/::YYYC (online-only).

On Fri, Jun 12, 2015 at 3:32 AM, piqoni <notifications@github.com> wrote:

> Around 60 commits ago, markdown worked in notes. ** bold ** would show
> *bold*, but in the latest version it doesn't.
> Something broke or was it intentional?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kobotoolbox/enketo-express/issues/222>.
>

-- 
-- 
*Revolutionizing data collection since 2012.*

Enketo <https://enketo.org/>    |    LinkedIn 
<http://www.linkedin.com/company/enketo-llc>    |    GitHub 
<https://github.com/enketo>    |    Twitter <https://twitter.com/enketo>    
|    Blog <http://blog.enketo.org/>
