### ISSUE TITLE
Form as app 

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#224]
The XForm format is so powerful that it could realistically be used to create form-as-tools that produce a diagnosis/outcome instead of a record. Such a tool can also be used as a guide to follow a complex flow-chart or protocol. It could be used for example to run a medical protocol, conduct a sanitary survey of a water well, or calculate the tips in a restaurant. In its simplest form an Enketo form could be made available without a submit button and introduce a special note appearance to style the final outcome.

**Comment by craigappl** [comment]
@MartijnR 

This issue has been on my mind for some time. I think the Form in pages example is fantastic. I also see the need to identify some type of offline menu that allows FLWs or clinicans to navigate to a particular Enketo form. Currently, the user would have to bookmark each form and flip through those bookmarks to find the protocol that they need to follow. 

Would it be possible to create a lightweight web app that uses the same Enketo offline technology to query all of the available Enketo forms within a user's KoboCollect, Ona.io or ODK Aggregate account and presents them in a clickable menu? This menu could act as a home screen for the form as App and could be further configurable in the future. 

For example future features may include:
- Show the status of queued submissions for each form
- Process all queued submissions for all forms from the menu screen
- Instead of automatically loading all forms in a user's account, allow administrators to choose whether to make each form available offline.
- Setup a form flow so users could be automatically redirected to another form or back to the home menu

**Comment by MartijnR** [comment]
Thanks Craig! Some interesting ideas here.

Yes, it would be possible to do this, just making use of the OpenRosa formlist API that the servers follow. I once did a quick bad demo in Enketo Legacy. Still online here: https://enketo.org/forms (though the 'portal' itself is not offline-capable).

> Show the status of queued submissions for each form
> Process all queued submissions for all forms from the menu screen
However, the idea is to not create any records :). It's a great idea for the ODK Collect mobile app alternative based around Enketo though. Definitely feasible (even in the web app, though I think it might be better reserved for the mobile app).

> Instead of automatically loading all forms in a user's account, allow administrators to choose whether to make each form available offline.
That's an interesting idea (I see it as something separate, and for the mobile app). The /formList could include a property that indicates the form should be downloadable to the app. On the other hand using 'Projects' to group forms might cater to this use case too.

> Setup a form flow so users could be automatically redirected to another form or back to the home menu
Yes, that would be a very cool feature. It would mean we have an easy way to deal with performance issues too, as it will allow you to split up forms. We could even use Enketo's dynamic defaults feature to pass values between forms in the redirect link.

Adding the functionality as described in the first post to the web app would be interesting if combined with a solid way of adding a form to the homescreen (this is solid already - but it needs to become easier). So a form is an app. Once it's there, users won't know the difference.

**Comment by enketo-issue-mover** [comment]
This issue was moved to enketo/enketo-express#33
