### ISSUE TITLE
Translations not shown, only translation keys

### ISSUE THREAD

**Issue by mraminemx** [kobotoolbox/enketo-express#228]
only variables names are shown instead of values.
example "formfooter.submit.btn" instead of "Submit"
![to del](https://cloud.githubusercontent.com/assets/7932387/8231221/9205286a-15b6-11e5-8e2b-d508276b450c.png)

**Comment by MartijnR** [comment]
Thanks. I've seen this issue occasionally but have not been able to reproduce it reliably.

Try restarting Enketo, or starting it without pm2. Does that resolve it?

Does it happen in the online-only views as well? E.g. localhost:8005/::YYYP (check the button).

**Comment by jflaming** [comment]
We had the same issue, but I can't help too much anymore, I just did a git pull and rebuild with grunt and it went away.

**Comment by MartijnR** [comment]
Thanks. Yes, that's the "problem". It just goes away by itself, which makes
it impossible to investigate.

On Thursday, June 18, 2015, R. Jay Flaming <notifications@github.com> wrote:

> We had the same issue, but I can't help too much anymore, I just did a git
> pull and rebuild with grunt and it went away.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kobotoolbox/enketo-express/issues/228#issuecomment-113320515>
> .
>

-- 
-- 
*Revolutionizing data collection since 2012.*

Enketo <https://enketo.org/>    |    LinkedIn 
<http://www.linkedin.com/company/enketo-llc>    |    GitHub 
<https://github.com/enketo>    |    Twitter <https://twitter.com/enketo>    
|    Blog <http://blog.enketo.org/>

**Comment by mraminemx** [comment]
I test that jflaming said but I still have the same problem, any others ideas ?

**Comment by MartijnR** [comment]
Will check when I have time. So you are using the vagrant build from this repo, right?

**Comment by mraminemx** [comment]
yes

**Comment by jflaming** [comment]
have you tried running it under grunt develop rather than npm?

**Comment by mraminemx** [comment]
that's what I did exactly :
> git pull && git submodule update --init --recursive
> grunt

**Comment by MartijnR** [comment]
may be linked to #208

**Comment by MartijnR** [comment]
@mraminemx could you please try again with the latest vagrant script (make sure to `vagrant destroy` first)?

I've changed the script. You now have to manually start enketo after the script is complete:
```bash
vagrant ssh
cd /vagrant
npm start
```

There really isn't a reason to use pm2 in the VM, and this was very likely the cause of the issue (though I couldn't reproduce it with the vagrant VM). The vagrant VM is not suitable for production use, just for testing and development (and you don't need pm2 in those scenarios). If you do want to run it with pm2 you could do this:

```bash
vagrant ssh
pm2 start /vagrant/app.js -n enketo
```
In that case, you may not experience the translation issue any more because, unlike with the previous vagrant script, pm2 will not be running as root.

**Comment by MartijnR** [comment]
reopen when needed

**Comment by MartijnR** [comment]
Some progress! @esmail 

I ran into this again on a new production server installation. Finally figured how to reproduce and resolve. Seems like a pm2 bug. It is related to how the app is started.

To reproduce the bug:
```bash
pm2 kill
pm2 start ~/enketo-express/app.js -n enketo
```

To workaround the bug:
```bash
cd ~/enketo-express
pm2 kill
pm2 start app.js -n enketo
pm2 save
# all should be good now, test by rebooting
sudo shutdown -r now
```
