### ISSUE TITLE
Customize Enketo form

### ISSUE THREAD

**Issue by LG7119** [kobotoolbox/enketo-express#264]
Hi Martijn,

I installed KoBoToolbox using Vagrant and Virtualbox on a local computer and everything was working fine. However, I cannot customize the Enketo form (such as changing font face / size, etc.) through XLS form definition due to its limitation. Just wondering if there is a better way to do this magic thing, for example, by modifying the style sheet. I looked through GitHub website but could not find the appropriate documentation to instruct how to do this. 

Kind regards
Lesley

**Comment by MartijnR** [comment]
Hi Lesley,

This would require developing a custom theme that extends one of the
existing themes. It can be quite easy. There is some guidance here:
https://github.com/kobotoolbox/enketo-express#themes

However, it can also become rather hard, for custom themes that go beyond
just changing colors and fonts if you want to maintain all the features of
the current themes. This is because you'll have to keep in mind all the
different contexts for a theme:
1. non-touchscreen vs touchscreen (add ?touch=true during development)
2. default one-page-mode and multiple-pages-mode
3. right-to-left form language vs left-to-right form language (!) - also
the UI-language may have a different directionality
4. screen view vs. print view
5. questions inside a (nested) repeat group have a different background
6. large screen size --> smaller screen size ---> smallest screen size
7. question in valid vs. invalid state

Enketo themes are monsters basically...

Good luck!

On Wed, Jul 22, 2015 at 12:32 AM, LG7119 <notifications@github.com> wrote:

> Hi Martijn,
>
> I installed KoBoToolbox using Vagrant and Virtualbox on a local computer
> and everything was working fine. However, I cannot customize the Enketo
> form (such as changing font face / size, etc.) through XLS form definition
> due to its limitation. Just wondering if there is a better way to do this
> magic thing, for example, by modifying the style sheet. I looked through
> GitHub website but could not find the appropriate documentation to instruct
> how to do this.
>
> Kind regards
> Lesley
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kobotoolbox/enketo-express/issues/264>.
>

-- 
-- 
*Revolutionizing data collection since 2012.*

Enketo <https://enketo.org/>    |    LinkedIn 
<http://www.linkedin.com/company/enketo-llc>    |    GitHub 
<https://github.com/enketo>    |    Twitter <https://twitter.com/enketo>    
|    Blog <http://blog.enketo.org/>

**Comment by LG7119** [comment]
Hi Martijn,

Thanks very much for your reply. From my understanding, KoBoToolBox has Enketo Express built-in. To be able to create a custom theme, should I install Enketo Express and KoBoToolBox separately? 

Lesley

**Comment by MartijnR** [comment]
Enketo Express is a separate app. I think you may be referring to the KoBo Vagrant VM which will install all required apps for KoBoToolbox. 

However, when using Enketo and KoBoCAT, KoBoForm in production, I'd personally always install Enketo on a separate server (and not use Vagrant to build). Here are very detailed installation instructions for an Enketo production server: http://blog.enketo.org/install-enketo-production-ubuntu/

**Comment by LG7119** [comment]
Hi Martijn,

Thanks for providing the hyperlink to the instructions for installing Enketo production server. We have a feeling that self installation might not be a practical way for us due to the limited resource for server maintenance. We are planning to collect patient survey data in the daily clinic and upload them to another database management system so that clinicians will be able to see the results in their clinic room without the long delay. Thus we need to avoid the downtime during the clinical time. We have installed KoBo Vagrant VM in a dedicated workstation running Windows 7 Professional SP1 and so far everything seems working fine. At the moment, we are thinking to make a little improvement in Enketo form design by changing the font size / type and color. Would you please recommend us if there is a better way to achieve this purpose with KoBo Vagrant VM installed?

Kind regards
Lesley

**Comment by MartijnR** [comment]
Hi Lesley,

You'd have to port enketo-express, create a custom theme, and then change the `git remote origin` of Enketo Express inside your VM. Then pull your changes.
