### ISSUE TITLE
Group Labels centered instead of left-aligned

### ISSUE THREAD

**Issue by jbonica** [kobotoolbox/enketo-express#331]
I just noticed that when we updated to newest Enketo, Group Labels are now centered (see Screenshot). Is this a bug or a feature? Thanks!
![group_label_centered](https://cloud.githubusercontent.com/assets/8268232/10647735/285ad612-7808-11e5-850c-471b491b0a72.PNG)

**Comment by MartijnR** [comment]
Ah yes indeed. Will revert back to previous state. Thanks!

On Wed, Oct 21, 2015 at 1:27 PM, Jim Bonica <notifications@github.com>
wrote:

> I just noticed that when we updated to newest Enketo, Group Labels are now
> centered (see Screenshot). Is this a bug or a feature? Thanks!
> [image: group_label_centered]
> <https://cloud.githubusercontent.com/assets/8268232/10647735/285ad612-7808-11e5-850c-471b491b0a72.PNG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kobotoolbox/enketo-express/issues/331>.
>

-- 
-- 
*Revolutionizing data collection since 2012.*

Enketo <https://enketo.org/>    |    LinkedIn 
<http://www.linkedin.com/company/enketo-llc>    |    GitHub 
<https://github.com/enketo>    |    Twitter <https://twitter.com/enketo>    
|    Blog <http://blog.enketo.org/>
