### ISSUE TITLE
Max() function error

### ISSUE THREAD

**Issue by smusula** [kobotoolbox/enketo-express#394]
Is the max() function supported on Enketo Express? We're getting the error message below when loading a form that has this function which works in ODK Collect.

![screen shot 2016-01-29 at 4 26 04 pm](https://cloud.githubusercontent.com/assets/4832172/12676681/1146a7c6-c6a5-11e5-8683-4d27a25e1ca9.png)

Is it possible for Enketo Express to display something like `function not supported` for functions that work on ODK collect but not Enketo Express this might be helpful to users who are using these functions.

**Comment by MartijnR** [comment]
I think it's supported. Try it out.

Enketo actually supports many more XPath functions than odk collect.

This error message is probably related to usage or a bug in the function.
Please let me know what you find out, so we can rectify asap if necessary.
On Jan 29, 2016 8:43 AM, "Sylvia Musula" <notifications@github.com> wrote:

> Is the max() function supported on Enketo Express? We're getting the error
> message below when loading a form that has this function which works in ODK
> Collect.
>
> [image: screen shot 2016-01-29 at 4 26 04 pm]
> <https://cloud.githubusercontent.com/assets/4832172/12676681/1146a7c6-c6a5-11e5-8683-4d27a25e1ca9.png>
>
> Is it possible for Enketo Express to display something like function not
> supported for functions that work on ODK collect but not Enketo Express
> this might be helpful to users who are using these functions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kobotoolbox/enketo-express/issues/394>.
>

-- 
-- 
*Revolutionizing data collection since 2012.*

Enketo <https://enketo.org/>    |    LinkedIn 
<http://www.linkedin.com/company/enketo-llc>    |    GitHub 
<https://github.com/enketo>    |    Twitter <https://twitter.com/enketo>    
|    Blog <http://blog.enketo.org/>

**Comment by smusula** [comment]
@MartijnR we tested these on various forms and got the same error message on all the forms that had the function. Here's a link to a simple XLSForm that we created to replicate this: [https://docs.google.com/spreadsheets/d/1f4rzBi-k0nAZ1vBu91shRRgL00K-tUYhSTIBiQVuwgw/edit?usp=sharing](https://docs.google.com/spreadsheets/d/1f4rzBi-k0nAZ1vBu91shRRgL00K-tUYhSTIBiQVuwgw/edit?usp=sharing). Thanks

**Comment by MartijnR** [comment]
Great. Thanks. I will check it out (next week).
On Jan 29, 2016 10:07 AM, "Sylvia Musula" <notifications@github.com> wrote:

> @MartijnR <https://github.com/MartijnR> we tested these on various forms
> and got the same error message on all the forms that had the function.
> Here's a link to a simple XLSForm that we created to replicate this:
> https://docs.google.com/spreadsheets/d/1f4rzBi-k0nAZ1vBu91shRRgL00K-tUYhSTIBiQVuwgw/edit?usp=sharing.
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kobotoolbox/enketo-express/issues/394#issuecomment-176801427>
> .
>

-- 
-- 
*Revolutionizing data collection since 2012.*

Enketo <https://enketo.org/>    |    LinkedIn 
<http://www.linkedin.com/company/enketo-llc>    |    GitHub 
<https://github.com/enketo>    |    Twitter <https://twitter.com/enketo>    
|    Blog <http://blog.enketo.org/>

**Comment by MartijnR** [comment]
[fixed!](https://odk.enke.to/preview?form=http://23.21.114.69/xlsform/downloads/tmp3yQiT0/max.xml)

Thanks!
