### ISSUE TITLE
1 page only printout on Firefox web browser

### ISSUE THREAD

**Issue by smusula** [kobotoolbox/enketo-express#408]
One is only able to print the first page (on screen), of a survey when the print function on Enketo is used in Firefox:

![printing_webforms_firefox](https://cloud.githubusercontent.com/assets/4832172/12776236/69befa66-ca65-11e5-858f-d2ec05ae1838.gif)

On Chrome, the entire survey is printed:

![printing_webforms](https://cloud.githubusercontent.com/assets/4832172/12776258/85810a0a-ca65-11e5-9d54-158ffcc3da6e.gif)

Tested this on this web form: https://enketo.ona.io/_/#Y0XH
 @MartijnR have you experienced this before?

**Comment by MartijnR** [comment]
Thanks @smusula. I'm not aware of this (because browser updates frequently break printing functionality). I was able to reproduce it the widgets form as well.

This will not be considered very urgent (because of the use case for printing, users can simply switch to Chrome or Edge when they want to print), so it may take a while before we can look at this.

**Comment by MartijnR** [comment]
I only know see how cool those gifs are! :+1:

**Comment by smusula** [comment]
@MartijnR Thanks for the quick response, I've asked them to use Chrome. Will be using gifs to report issue from now on :smile:

**Comment by MartijnR** [comment]
Confirmed to still be present in latest FF. Also not enough space for first question.

**Comment by MartijnR** [comment]
setting `.main` to `display: block;` seems to resolve issue with Formhub (and similar themes). 

* [ ] investigate side effects
* [ ] check Grid Theme
