### ISSUE TITLE
remove powered by enketo

### ISSUE THREAD

**Issue by iahmedani** [kobotoolbox/enketo-express#447]
Hi Martin,

Is it possible to remove "powered by enketo" if so please guide me as I tried in config.json, login page directs to location example.com/..... 

please advice.

**Comment by MartijnR** [comment]
I'm not a lawyer, but I believe that would be illegal... See under License
in readme.md. Contact me at martijn@enketo.org to discuss why your
organization is exempt (I don't actually know what organization you're
working for of course).

On Fri, Mar 18, 2016 at 2:09 PM, iahmedani <notifications@github.com> wrote:

> Hi Martin,
>
> Is it possible to remove "powered by enketo" if so please guide me as I
> tried in config.json, login page directs to location example.com/.....
>
> please advice.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/kobotoolbox/enketo-express/issues/447>
>

-- 
-- 
*Revolutionizing data collection since 2012.*

Enketo <https://enketo.org/>    |    LinkedIn 
<http://www.linkedin.com/company/enketo-llc>    |    GitHub 
<https://github.com/enketo>    |    Twitter <https://twitter.com/enketo>    
|    Blog <http://blog.enketo.org/>

**Comment by iahmedani** [comment]
Ok this was just for knowledge base query, sorry for inconvenience is caused due to my question

**Comment by MartijnR** [comment]
No problem :). It's a fine question to ask!
