### ISSUE TITLE
Markdown and <output> don't work together

### ISSUE THREAD

**Issue by ivermac** [kobotoolbox/enketo-express#451]
We have a user who has markdown in his/her xls form on the label column and it doesn't render as expected. Does enketo express support markdown in xls forms?

**Comment by MartijnR** [comment]
yes, it is supported in all labels and hints

On Tue, Mar 22, 2016 at 1:13 AM, Mark Ekisa <notifications@github.com>
wrote:

> We have a user who has markdown in his/her xls form on the label column
> and it doesn't render as expected. Does enketo express support markdown in
> xls forms?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/kobotoolbox/enketo-express/issues/451>
>

-- 
-- 
*Revolutionizing data collection since 2012.*

Enketo <https://enketo.org/>    |    LinkedIn 
<http://www.linkedin.com/company/enketo-llc>    |    GitHub 
<https://github.com/enketo>    |    Twitter <https://twitter.com/enketo>    
|    Blog <http://blog.enketo.org/>

**Comment by ivermac** [comment]
Cool, we'll test then give you feedback

**Comment by ivermac** [comment]
So we've tested this feature and it's working on normal text. A client was trying to refer a question name on a label on an xls form and he was using markdown formatting and it failed to work for him.The label on the xlsform is `How old is *${name}*`. If `${name}` is John Doe, it renders as `How old is *John Doe` rather than the expected  - How old is **John Doe**

**Comment by MartijnR** [comment]
Ah ok. Let's leave that here as a bug then. Thanks. 

I guess it should generate <em><span class="or-output">John Doe</span></em> but Enketo probably doesn't pick up content in tags. 

I don't think I'll be fixing this any time soon, so PR is welcome. It's done in enketo-transformer and there are lots of markdown tests, so that's good.

**Comment by ivermac** [comment]
cool

**Comment by MartijnR** [comment]
This turned out to be a regression and was something some users were relying on. It's almost fixed. 

* [ ] add test

**Comment by ivermac** [comment]
Cool
