### ISSUE TITLE
if max-size request fails or max-size value updates, form media is cleared from the database

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#456]
Not necessarily Enketo related. Reported by OC (custom server). I can reproduce with their Enketo server only. Also reported by @xanf when using his custom server.

**Comment by MartijnR** [comment]
<img width="460" alt="screen shot 2016-03-23 at 1 37 22 pm" src="https://cloud.githubusercontent.com/assets/627350/13998360/71595a06-f0fc-11e5-92d8-6f801c98f740.png">

**Comment by MartijnR** [comment]
The first time, the resources are correct population in db in both surveys and resources tables.
The second time, the resources in the survey table are set to null, and then removed from the resources table (as @xanf outlined, this happens in an update call)

**Comment by xanf** [comment]
hi again @MartijnR 
So, I've debugged it more, and was able to reproduce it on your enke.to setup.

Two things should happen:
1) offline mode should be enabled
2) call to `https://enke.to/submission/max-size/::widgets` should either fail or return something like 0 or null

What will happen on next offline mode launch:
`updateMaxSubmissionSize` will be launched. Since `survey.maxSize` is false (that is required to reproduce a problem) getMaximumSubmissionSize will be executed, launching `store.survey.update( survey )` - where the issue I've described to you earlier happens (data is removed)

On my custom server I'm experiencing this issue because max-size call is not implemented and fails

**Comment by MartijnR** [comment]
:D I was just about to write the same thing to you! :+1:  The other custom server had the same problem.

Am committing fix shortly!

**Comment by MartijnR** [comment]
base64-encoded blobs are sent to _updateFile before being converted back to Blob
