### ISSUE TITLE
How to import saved data of certain form on other computer

### ISSUE THREAD

**Issue by iahmedani** [kobotoolbox/enketo-express#469]
Hi Martin.

Can you please advice is it possible to import data (saved as draft in offline mode) in enketo form from another computer by export it. Or any other way so data can be reviewed.

**Comment by MartijnR** [comment]
Enketo doesn't offer imports. However, the structure of the (yet unannounced) export feature is now the same as the structure ODK Collect saves data in. So you can use whatever method is supported by your server (e.g. KoBo, ODK Aggregate, Ona). You may find an issue, because the feature is so new. If you do, please try the same method in ODK Collect (by copying the files manually - thereby creating an 'export'). If you notice a bug, that ODK Collect doesn't have, please open an issue for this.
