### ISSUE TITLE
Getting 401 when checking for survey update

### ISSUE THREAD

**Issue by ivermac** [kobotoolbox/enketo-express#482]
Hi @MartijnR , so I noticed that when `require_auth` is set to true on onadata and a user has already authenticated, the user gets a 401 when he/she loads the form on enketo - the 401 is triggered when enketo tries to check for a survey update as seen on the screenshot below:
<img width="1279" alt="screen shot 2016-04-20 at 10 59 46" src="https://cloud.githubusercontent.com/assets/1128227/14667389/a1d22b76-06e7-11e6-8262-bf6a49158329.png">
On further investigation I noticed by adding `survey.cookie = req.headers.cookie;` above [this line](https://github.com/kobotoolbox/enketo-express/blob/master/app/controllers/transformation-controller.js#L92) seems to fix problem - making sure the survey object has a property `cookie` whose value is `req.headers.cookie` as it's done also on the same file on [this line](https://github.com/kobotoolbox/enketo-express/blob/master/app/controllers/transformation-controller.js#L46). Do you think this is a valid fix?

**Comment by MartijnR** [comment]
Interesting! When looking at the code, it seems like we should have the same problem with OpenRosa authentication. I'd like to look into that.

Your proposed fix seems good to me. PR welcome.

I think the code in that controller could use some refactoring. It might be be better to pass `req` to _getSurveyParams (instead of `req.body`), and then populate both survey.cookie and survey.credentials there (only). Even though they are not always required, it makes the code cleaner and the performance impact should be negligible. I may add that to your commit (unless you are able to do this && test with regular OpenRosa authentication, e.g. in ODK Aggregate of course!).

**Comment by ivermac** [comment]
@MartijnR I have added a [PR](https://github.com/kobotoolbox/enketo-express/pull/484) for this issue. I haven't tested with regular OpenRosa authentication though

**Comment by MartijnR** [comment]
Confirmed that the issue you found was also present with regular OpenRosa authentication. Big bug!

And your PR also fixed that one! 👍
