### ISSUE TITLE
Error in Chrome when trying to edit a submission with encoding

### ISSUE THREAD

**Issue by jeverling** [kobotoolbox/enketo-express#529]
Steps to reproduce:

- Create a form like this:
`curl -u "username:password" -d "xls_url=http://jeverling.de/myform.xls" https://kc.kobotoolbox.org/api/v1/forms`

- write down the `uuid` value from the response and create an XML without encoding like this (note that `kobocat` prepends an underscore to the root node name when importing a form from URL, e.g. `_myform`):
`echo '<?xml version="1.0" ?><_myform id="myform"><formhub><uuid>{UUID-FROM-RESPONSE-ABOVE}</uuid></formhub><encoding>None</encoding><meta><instanceID>uuid:without-encoding</instanceID></meta></_myform>' > without-encoding.xml`

- and another one with an encoding:
`echo '<?xml version="1.0" encoding="UTF-8"?><_myform id="myform"><formhub><uuid>{UUID-FROM-RESPONSE-ABOVE}</uuid></formhub><encoding>UTF-8</encoding><meta><instanceID>uuid:with-encoding</instanceID></meta></_myform>' > with-encoding.xml`

- POST both to `kobocat`:
`curl -u "username:password" -F "xml_submission_file=@without-encoding.xml" "https://kc.kobotoolbox.org/api/v1/submissions"`
`curl -u "username:password" -F "xml_submission_file=@with-encoding.xml" "https://kc.kobotoolbox.org/api/v1/submissions"`

- open the project in `kobocat` and look at the data. Everything is displayed fine. When you click on "Edit", `enketo` shows the following error message for the submission with encoding: `Error trying to parse XML record. Different encoding`

I tested this in Chrome 46.0.2490.80 and Chromium 51.0.2704.106 (64bit Linux). 
In Firefox it works fine.

**Comment by MartijnR** [comment]
Interesting! Thanks for reporting this. 

I believe UTF-8 is the default (when the declaration is missing), so that means we should be able to support both the case you describe.

We probably do not need to support editing a record with a different encoding from the encoding specified in the XForm. 

To assess whether this work is something a sponsor might be interested in funding: Are you able to reproduce this with records submitted with either Enketo or ODK Collect?

* [ ] when merging a record consider no encoding attribute as UTF-8
* [ ] check if encoding of XForm is copied to XML model when it's extracted with XSLT

**Comment by MartijnR** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Document/characterSet

https://github.com/hareko/js-merge-xml/pull/13 (waiting for merge and new version to be published on npm)
