### ISSUE TITLE
Offline urls seem not to work

### ISSUE THREAD

**Issue by ivermac** [kobotoolbox/enketo-express#538]
Hi Martijn,
One of the Ona users noticed that an offline url wasn't working since and I tried to replicate the error using the enketo id of a url - https://enke.to/::YYye - you sent us a couple of days ago. I was able to successfully replicate the error when trying to access the url without internet. Are you able to replicate the error yourself? Below is a screenshot of the replicated error. Thanks
<img width="968" alt="screen shot 2016-07-29 at 23 13 53" src="https://cloud.githubusercontent.com/assets/1128227/17262095/1d8da3c8-55e2-11e6-9da6-6dc9c5852263.png">

**Comment by MartijnR** [comment]
OUch. Thanks. I am able to reproduce this too. Seem to be caused by translation file. Will try to fix with a quickness.

<img width="484" alt="screen shot 2016-07-29 at 2 41 56 pm" src="https://cloud.githubusercontent.com/assets/627350/17262773/b61be8f4-559a-11e6-8bf6-2af56cbbc975.png">

**Comment by MartijnR** [comment]
I am so glad you found and reported is before the weekend! Thanks a lot. All is good again now. It will take up to an hour after deploying the fix for the server-cached manifests to update themselves automatically.

If you want to speed this up further, go into the redis cache instance with redis-cli and delete the manifests for each language, e.g. `del ma:en_manifest`.

**Comment by ivermac** [comment]
Wow! that was fast! Thanks for responding and fixing the issue in lightning speed.
