### ISSUE TITLE
persistant cookie

### ISSUE THREAD

**Issue by danielduhh** [kobotoolbox/enketo-express#658]
POST /transform/xform does not keep cookie through request

https://github.com/kobotoolbox/enketo-express/blob/master/app/lib/communicator/communicator.js#L112

cookie property is already attached to survey parameter. Add a header object to options & check for cookie, if it exists add as property to header object

```
var options = {
        url: getFormListUrl( survey.openRosaServer, survey.openRosaId ),
        auth: survey.credentials,
        // Formhub has a bug and cannot use the correct HEAD method.
        method: config[ 'linked form and data server' ][ 'legacy formhub' ] ? 'get' : 'head',
        headers: {}
    };

    // add cookie if it exists
    survey.cookie ? options.headers["cookie"] = survey.cookie : "";

**Comment by MartijnR** [comment]
Thanks! Which server can the issue reproduced with. Ona?

**Comment by danielduhh** [comment]
This issue was encountered while using enketo-express w/ custom external authentication

**Comment by MartijnR** [comment]
Thanks. Can you please clarify which request it is not added to? Formlist?, XForm itself? Manifest? Media resources in manifest? 

I'm trying to understand it better, because there are servers that use external authentication and they do not have a problem. This could be because they decided to keep some resources unprotected, so that's what I'd like to find out. Thanks in advance!

**Comment by MartijnR** [comment]
Though I couldn't reproduce it quickly enough (I think because the servers that use external authentication, are not very strict with obtaining form resources....), it makes a lot of sense that this is a bug. So I applied your fix (slightly different).  Let me know if doesn't work (or send a PR).

Thanks!

P.S. If your app is not published on https://enketo.org, I'd be glad to do so. Just send me a link and logo.
