### ISSUE TITLE
iFrame 'submissionsuccess' post message does not fire from offline-capable iframe

### ISSUE THREAD

**Issue by chrismclarke** [kobotoolbox/enketo-express#670]
I was just testing out the iframe post message functionality from the demo found that setting the iframe source as `https://enke.to/_/?parentWindowOrigin=http%3A%2F%2Fenketo.github.io#widgets` correctly fires the 'edited' event message but does not fire any 'submissionsuccess' messages

**Comment by MartijnR** [comment]
Thanks!

**Comment by MartijnR** [comment]
I realize now that this is actually by design. Offline-capable views are not really meant for iframes (hence there is no [API endpoint](https://apidocs.enketo.org/v2) for it).

What is your use case? Is the parentWindow offline-capable?

**Comment by chrismclarke** [comment]
Yes I embedded the iframe in an offline cordova mobile app. An early proof-of-concept app I put together around this design can be found here: https://play.google.com/store/apps/details?id=com.stats4sd.dataloopsdemo
In a more recent version forms are published to second database and then sync'd back down in real time so actually a submissionsuccess message isn't vital (although a 'submission-queued' or similar would be great for knowing how many submissions are pending and to perhaps keep the iframe open/hidden until submission success)

**Comment by MartijnR** [comment]
Thanks. Very interesting project!

I'd be happy to help figure out how this could be facilitated either in this (master) app, or in a fork (which of course you'd like to avoid). 

When you are clear about what you require, feel free to open an issue (or re-open this one). At first glance, maybe you'd like to be able to poll the form to get the number of records left in the queue? Maybe for draft as well as final records. 

(Let me know when you're ready for the app to be promoted on the enketo.org front page! :-) )

**Comment by chrismclarke** [comment]
Hi Martijn, thanks again for your feedback and sorry for my slow response. I'm just in the process of reviving this project and trying to decide how best to proceed on a couple issues:

1. Passing variables into offline forms
I can think of a few different use cases where the user may want to pass a variable into a form (such as locally cached user info that can be used across multiple forms). I've seen quite a lot of discussion around this last year and whether it will mess up the cache (e.g. #386, #406 ). I've tried implementing with crafting a url and indeed it doesn't work. I saw that there was commit to close 386 however on the changelog it says not implemented. Is this still the case? If not how can I go about using it? 

2. Polling forms
As discussed in the thread above I can think of a few things that it would be useful to do
a) receive notification to parent on successful form submission
b) poll form to get number of records left in queue
c) poll form to check last updated and/or whether updates available (likely info from console logs on form open would be sufficient, such as 'cached survey up to date ' checksum)

Would be great to know what you think, particularly with regards to what can be done already.

**Comment by MartijnR** [comment]
Hi Chris,

1. This was implemented but I think I may have left it out of the changelog because it was considered to be only useful by OpenClinica. If I remember correcty it only stores the query variable name that is set in config.json under ["query parameter to pass to submission"](https://github.com/kobotoolbox/enketo-express/tree/master/config#query-parameter-to-pass-to-submission). I probably shouldn't have included this feature in the main repo. However, this technique could be used with the same limitations for your use case perhaps (in a fork).

2. I think these features could be added quite easily in a fork, using new postMessage listeners (and enabling these in offline-capable views). 

I am not sure which of these features should be in included in Enketo Express, so probably best to just go ahead in a fork and maybe try to put as much as possible in a separate new module to avoid merging conflicts.

**Comment by chrismclarke** [comment]
Really useful, thanks. I'll give that a go and let you know how i get on.
