### ISSUE TITLE
Update Redis installation method in installation guidance

### ISSUE THREAD

**Issue by davidpiedrarojas** [kobotoolbox/enketo-express#725]
Hello, I'm trying to install enketo-express on a ubuntu server, I followed the steps in this guide https://blog.enketo.org/install-enketo-production-ubuntu/, but when the redis servers start one of them don't work. Al first was the main process, then after a name change the cache stop working. I run the service start command and says that the process is running but get a connection refused.

If I continuethe rest of the guide, whe I try run the grunt command there's a Econnrefused 127.0.0.1:6380.

Do you have any suggestions?

Thanks.

David

**Comment by MartijnR** [comment]
Hi David,

I wonder if what you are running into is that the redis-server is using systemd instead of upstart to run services. If so, this is the new recommendation for installing redis: 569a789c6c5b942d1c2b8625fbb2ddded34ec859

I want to update the installation guidance to using systemd (and Ubuntu 16.04) but don't have time to test this at the moment as it takes a lot of time to do. The PPA from which redis is installed in the guidance, is no longer available I believe.

**Comment by davidpiedrarojas** [comment]
Thanks, your recommendation worked! Enketo is now up.

**Comment by MartijnR** [comment]
Great. Thanks. I rename this issue.

**Comment by davidpiedrarojas** [comment]
Where do I find the enketo api url for ODK? I've tested a couple and with no luck. I've used http://xxx.xxx.xxx.xxx:8005/ and get "Resource not found in database" and http://xxx.xxx.xxx.xxx:8005/api/v1/ and get "There was an error obtaining the webform. (message:Bad Request. Server URL is not a valid URL.)".

Thanks

David

**Comment by MartijnR** [comment]
Your second one is correct. The issue is likely that from the VM or host on which you have installed Enketo, the ODK Aggregate server is not reachable. When ODK Aggregate makes the API call (to /survey) it passes it's own server_url as a parameter. This is where Enketo will attempt to obtain the webform. So you'd have to do some network configuration to get the 2 apps to communicate with each other (locally, I presume).

**Comment by davidpiedrarojas** [comment]
Thank you for all your help.

**Comment by MartijnR** [comment]
updated blog post
