### ISSUE TITLE
Manually clearing dates does not clear in model

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#794]
So when not using reset button

**Comment by pbowen-oc** [comment]
We're seeing a similar problem with manually changing date values in general. If I type a new date value and hit enter, the value is reflected in the Query Widget History and I see it if I close and reopen the from,  However, if I manually type a new date and click away to a new field, the value is not added to the history or pushed back to us.  The same thing happens if we click away to the Close button - the form closes without saving this last data change.  It seems like the enter key is actually interacting with the date picker and that's why it is correctly saving the value.

Note that even hitting enter isn't allowing me to reset the date field back to empty.
