### ISSUE TITLE
New repeats get progressively slower as the number increases

### ISSUE THREAD

**Issue by bmalina** [kobotoolbox/enketo-express#806]
Hi Martjin,

We have noticed that when the value of a repeat count is greater than 50 the form fails to load.
Is this something that can be fixed or is there a certain threshold that Enketo can handle?

Sample form: [repeat_count1.xlsx](https://github.com/kobotoolbox/enketo-express/files/1242450/repeat_count1.xlsx)
Browser: Chrome
Server: Ona

**Comment by MartijnR** [comment]
Hi @bmalina,

This is limitation of the device the form is used on (a repeat-count of 100 is fine on my fancy computer). It's probably CPU related. However, there may be scope to improve the performance by profiling and tweaking. These kind of exercises are quite time-consuming with an unknown result though. 

I wonder if creating so many repeats signifies an issue with the design of the survey.

**Comment by MartijnR** [comment]
@eshutoff wrote:

>last 4-5 months we experienced the issue with “group repeat” on Kobo and Ona, they use your service, so I think the problem is here. Tested in different browsers, even MS IE lol.
After 15 iterations of group repeat, every next opened with progressive delay, 25, 45, 90, 200 sec an so on. Just frozen page, scroll doesn’t work.
>The issue doesn’t relay to complexity of group, the group with only one question has the same problem.
> I tried to ask help of Kobo and Ona and ODK teams but still no success.

>Looking for your advice, guys, I like ODK and Enketo, but that is real problem for users!

>Best wishes, Eugene

**Comment by MartijnR** [comment]
Thanks @eshutoff! I don't have the funding to look into this at the moment, unfortunately.

**Comment by eshutoff** [comment]
Do you have any plans to fix this issue in future? When?

**Comment by MartijnR** [comment]
I'd like to, but it is not really possible to say when. It's mostly dependent on when one of Enketo's sponsors makes this a priority and funds it (e.g. Ona, Esri, OpenClinica, KoBo). Performance issues are always a bit difficult because it is really not possible to estimate how much time it will take to fix them. May be a few hours or maybe a few days. Sorry about that.

**Comment by eshutoff** [comment]
Hi again,

How much do you need? Maybe private money could help?

15 дек. 2017 г. 20:06 пользователь "Martijn van de Rijdt" <
notifications@github.com> написал:

**Comment by MartijnR** [comment]
Yes, certainly. Thanks for asking. My rates are published here: https://enketo.org/services/. Let's discuss over email. I don't think I have your email address. Mine is martijn @ enketo.org

**Comment by eshutoff** [comment]
Hi Martijn,

You have a good rate, slightly bigger than my wishes to fix the error in enketo code and previously generated by developers of enketo))) Do you have different rates for new features and for fixing existing errors?
Maybe you could request grant from NGOs for future support of service?



Best wishes, Eugene

**Comment by MartijnR** [comment]
> Maybe you could request grant from NGOs for future support of service?

Thanks for the suggestion. I don't have any doubt it will get fixed under funding from existing sponsors. Just a matter of time.

**Comment by MartijnR** [comment]
@bmalina, version 1.56.0 is a bit faster with large repeat count ([temporary link](https://odk.enke.to/preview?form=http://82.196.7.170/downloads/lvszzea0/repeat_count1.xml)), but I didn't find a clear culprit. There is a lot of DOM manipulation when adding a large amount of repeats, so it's always going to be slow. This is especially the case when complicated widgets such as the geo widget are inside the repeat.

>The issue doesn’t relay to complexity of group, the group with only one question has the same problem.

@eshutoff, I think your issue is actually not the same after all. I'd like to move it to its own issue, but I actually wasn't able to reproduce your issue with this [test form](https://docs.google.com/spreadsheets/d/1l5naGjnpi6_eDbob9PYBRkc-kW28rIhsNj_ICHxHu20/edit?usp=sharing). So I think it probably is related to some logic in the form. If you haven't given up on Enketo can you share a simple form with which you can reproduce it yourself when uploading to http://opendatakit.org/xiframe/ and clicking "Preview in Enketo"? This server always has the most cutting edge version of Enketo Express.

**Comment by eshutoff** [comment]
Hi Martijn,

I hope the holidays were perfect!

1) I uploaded the test form (attached) and one of actual forms - no any
issues! Great! But...
2) I uploaded the same simple test form to https://kobocat.unhcr.org and
https://kc.humanitarianresponse.info and have got delays just after 15-16
iterations :(

What could you recommend to do with it? I tried to communicate with support
of these sites but without success, they sent me to you :) Maybe you could
to motivate them to update the servers?


Best wishes, Eugene



Best wishes, Eugene

**Comment by MartijnR** [comment]
Hi Eugene,

Thanks for checking. The decision on when to update is really up to the organization that provides the service. Normally, they would do some internal testing before deploying, especially for 0.1.0 version increases. They always have to be careful not to introduce serious regressions (that definitely happen) as so many people depend on their service. So sorry, I cannot speed that up ;).

**Comment by MartijnR** [comment]
Noticing extreme slowdown with test form repeat-only-calculate.xml. 

It happened some time after Enketo Core 4.41.5

**Comment by eshutoff** [comment]
What kind of problem it could be? I'm sure this issue didn't exist before
Jul 2016. Maybe is there any ways to come round of it, to mitigate it?

Best wishes, Eugene

**Comment by MartijnR** [comment]
@eshutoff, usually a bug fix causes such a performance regression

@martijnr, the Jan 2018 issue is with caching repeat-info items that contain a `data-repeat-count` attribute. It is probably time to re-write `form.getRelatedNodes`.
