### ISSUE TITLE
OC only: Edit generic loading error screen

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#810]
<img width="608" alt="screen shot 2017-08-30 at 2 02 43 pm" src="https://user-images.githubusercontent.com/627350/29892501-f96f5abc-8d8b-11e7-9590-be49d957adc9.png">

OC to propose new text

**Comment by MartijnR** [comment]
if goto field is hidden:

<img width="608" alt="screen shot 2017-08-30 at 2 02 43 pm" src="https://user-images.githubusercontent.com/627350/29947904-387eb1ca-8e69-11e7-85de-30338de1a9ab.png">

**Comment by MartijnR** [comment]
Martijn to add translation refs

**Comment by MartijnR** [comment]
The strings are in https://github.com/OpenClinica/enketo-express-oc/blob/master/locales/en/translation.json under keys:

* alert.loaderror.msg1
* alert.loaderror.msg2
* alert.loaderror.msg1_plural
* alert.loaderror.msg2_plural

**Comment by MartijnR** [comment]
* [ ] martijn to check if translation-additions.json can be made to override translation.json

**Comment by pbowen-oc** [comment]
@MartijnR - Would we be able to change the order of the strings in this window? After working through our desired messaging, we would prefer to have the detailed error message listed first. This is not essential, though.

**Comment by MartijnR** [comment]
Yes, that's possible. That means we have to override the master showLoadErrors function in the OC fork. If we have to do that anyway, than we may as well just add completely new strings in translation-additions.json. So just share a design and we'll implement that.

**Comment by pbowen-oc** [comment]
@MartijnR - We're looking to display the following messages:

* If the field they are trying to view is currently hidden, the window will say:
"**Hold on a second...**

The item you are trying to access is currently hidden. Please use the View Query Only icon instead of the View Query Within Record icon to see it.

Please contact your support team with the link to this page and the error message above if you need further help."

* If the field they are trying to view is not on the form, the window will say:
"**Hold on a second...**

The item you are trying to access has been removed from this form. Please use the View Query Only icon instead of the View Query Within Record icon to see it.

Please contact your support team with the link to this page and the error message above if you need further help."

If allowing that is much more difficult than just supporting our custom text in the old format with the specific message at the end, please let me know and I'll re-word the text to fit the old format.

**Comment by MartijnR** [comment]
What should Enketo display if there are other loading errors as well?

**Comment by pbowen-oc** [comment]
@MartijnR - It could show the other error messages after/instead of the new messages we have created.

**Comment by MartijnR** [comment]
Ah yes. In that case, it's not hard to do this.

**Comment by pbowen-oc** [comment]
@MartijnR - Keeping the format as it is now, these are the message we want:

* If the field they are trying to view is currently hidden, the window will say:
"**Hold on a second...**

Please contact your support team with the link to this page and the error message below if you need further help.

The item you are trying to access is currently hidden. Please use the View Query Only icon instead of the View Query Within Record icon to see it."

*  the field they are trying to view is not on the form, the window will say:
"**Hold on a second...**

Please contact your support team with the link to this page and the error message below if you need further help.

The item you are trying to access has been removed from this form. Please use the View Query Only icon instead of the View Query Within Record icon to see it."

**Comment by MartijnR** [comment]
* [ ] let translations-additions.json become able to overwrite translation.json
* [ ] edit 'alert.loaderror.msg1' and 'alert.loaderror.msg2' and 'alert.gotonotfound' by adding these to translation-additions.json
* [ ] edit 'alert.gotohidden' in translation-additions.json

**Comment by MartijnR** [comment]
https://github.com/i18next/grunt-i18next/pull/8
