### ISSUE TITLE
OC only: reason for change

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#839]
* [x] remove remnants of old reason for change code
* [x] update OC api documentation
* [x] each user-control value change adds a reason-for-change field to new section at bottom of form (above close button)
* [x] the above also includes fields inside a repeat that was deleted
* [x] the above also works if the repeat = the page
* [x] the above also includes new fields with a new value in a newly created repeat
* [x] each reason-for-change field is essentially a special input field to add a 'reason' type discrepancy note. This takes care of submitting the reason-for-change values using existing functionality. This type of dn will not change the dn status. To be discussed whether the History should show the reason immediately.
* [x] when the next or go-to-last button is clicked all reason for change fields on the current page must have a value (and therefore must have added a dn change to the submission queue). If that's not the case: block + tbc
* [x] if a field is changed and the back/first page is clicked, the reason input of the other page is still shown. It might be best to also block navigation for first/back to avoid confusion.
* [x] same for when complete or close button is clicked (I think)
* [x] if there are multiple repeat instances on a page, somehow visually indicate which instance a reason question belongs to
* [x] exclude readonly fields, see what happens with Mean Diastolic pressure in Vitals form - No, seems to make sense to include all fields that have a dn widget
* [x] styling
* [x] exclude calculated fields
* [x] this should be enabled for: records that are complete (excluding readonly and noteonly)
* [x] if a repeat field is changed, and the repeat is removed before a reason has been entered for the field, the field should be removed from the list of reason inputs -  I wonder if we can do a check in reasons.fields to see if the element still exists and if not, remove the associated reason
* [ ] in the above case, we may also have to re-process repeat numbers - On hold as OC may want to do something different and not use repeat numbers
* [x] if repeat=page, creating a new repeat does something weird. see http://localhost:8005/single/fs/i/::YY8S - It should not automatically move to the next page if there are outstanding reasons to fill in - same as Next button

**Comment by pbowen-oc** [comment]
@MartijnR - I don't think we need to disable jumping to the last page entirely, but all page navigation buttons (as well as Close) should not work if there are any missing required reason for change value. If the user tries to leave the page when a reason for change is missing, a window should popup with a message telling them they need to enter all reasons to continue.

I think the History should show the reason as soon as it is submitted.

**Comment by MartijnR** [comment]
Thanks!

**Comment by MartijnR** [comment]
An issue (documenting for self) with deleting repeats. This is the cascade of events:

1. repeat gets deleted from view
2. repeat gets deleted from model
3. we detect the delete from the model and try to add a "reason" type comment to the _comment nodes
4. the repeat is already gone from the model so there is no node to add the comment and no way to submit it

**Comment by pbowen-oc** [comment]
@MartijnR - It should be fine to have special behavior for deleted repeating groups. When the user clicks the delete button, it can pop up a modal to collect the reason for that deletion. Collecting reasons for other changes should still work as we had discussed.

**Comment by MartijnR** [comment]
wrt Close/Complete behavior it probably makes sense to report missing reasons as missing required questions.

**Comment by MartijnR** [comment]
At this point, it is quite functional, and it would be good to get feedback before finalizing. I'll show tomorrow during the meeting and can prepare a branch on top of the latest oc-master branch to deploy if desired.

**Comment by MartijnR** [comment]
This feature can now be tested on branch `feature/reason-for-change-I` (which includes the latest master fixes until today).

**Comment by pbowen-oc** [comment]
@MartijnR - I demoed this today and the feedback was very positive.  We couldn't test the full workflow (saving & reopening) since our integration wasn't ready, but we should be able to run through that on Monday.

Here's our feedback so far:
1. Please add this heading to the RFC area at the bottom: "Looks like you've made some updates. Please tell us why:"
2. In the History widget, can you use a delta/triangle icon for RFC entries?
3. Fields populated by calculated values (that are visible on the form) are currently triggering RFC fields to appear on the form. We don't want these to have reasons for change added to them (since the source fields for the calculations are what the user will need to comment on).
4. For RG fields getting an RFC, we want to show the group number in parentheses after the label. For example "Medication Name (2)".
5. RG numbering should be updated in the RFC area if repeats are deleted.

There are a few other enhancements that we're interested in after that. We can discuss these in more detail next week. 
1. Add an apply to all option to the top of the RFC section.
2. Add a dropdown list to allow selecting a predefined reason instead of typing the text manually.
3. Show old value and new value after the field label for each field in the RFC area.
4. Make RFC use a configurable option. It would still only apply to Complete forms if it were used, but we'd pass a parameter in that determines whether to use it for a given form or not. If not used, previous Complete form behavior.

**Comment by MartijnR** [comment]
>Here's our feedback so far:

> Please add this heading to the RFC area at the bottom: "Looks like you've made some updates. Please tell us why:"
> In the History widget, can you use a delta/triangle icon for RFC entries?
> Fields populated by calculated values (that are visible on the form) are currently triggering RFC fields to appear on the form. We don't want these to have reasons for change added to them (since the source fields for the calculations are what the user will need to comment on).
> For RG fields getting an RFC, we want to show the group number in parentheses after the label. For example "Medication Name (2)".
> RG numbering should be updated in the RFC area if repeats are deleted.

There are a few other enhancements that we're interested in after that. We can discuss these in more detail next week.

> Add an apply to all option to the top of the RFC section.
> Add a dropdown list to allow selecting a predefined reason instead of typing the text manually.
> Show old value and new value after the field label for each field in the RFC area.
> Make RFC use a configurable option. It would still only apply to Complete forms if it were used, but we'd pass a parameter in that determines whether to use it for a given form or not. If not used, previous Complete form behavior.

**Comment by MartijnR** [comment]
* [ ] Add an apply to all option to the top of the RFC section. 
* [ ] Add a dropdown list to allow selecting a predefined reason instead of typing the text manually.
* [ ] Show old value and new value after the field label for each field in the RFC area.
* [ ] Make RFC use a configurable option. It would still only apply to Complete forms if it were used, but we'd pass a parameter in that determines whether to use it for a given form or not. If not used, previous Complete form behavior.

**Comment by pbowen-oc** [comment]
We can discuss this at our next meeting in detail, but we've refined our design for the RFC Apply to All feature.  Instead of a single Apply to All control at the top of the section, we'd put an Apply to All button next to each RFC field. When the user enters an RFC value, the button next to it would be enabled. Clicking it would copy the RFC value for that field and insert it into all of the other RFC fields currently on that page (whether the RFC field is current blank or has a value) and trigger submission of each of them (at least if it is represents a value change).

**Comment by pbowen-oc** [comment]
Let's bump "Show old value and new value after the field label for each field in the RFC area." to the top of this list. We're in a slight holding pattern with the items above it.

For old value and new value, we generally want to show the same text as in the History widget. The major difference is that for select/multi-select, we want to show the label(s) of the selection rather than the  name.

In case of long text for either the old or new value (or maybe just the combined string overall), we're thinking we'd like something where it truncates with an ellipses and expands when clicked (like how the History widget works).

**Comment by MartijnR** [comment]
just the first two initially

**Comment by MartijnR** [comment]
The apply to all functionality has been added and is ready for testing in `master`

**Comment by pbowen-oc** [comment]
Thanks, Martijn. I'll give you feedback after we can run through it.

One issue I just noticed is with RFC on non-Grid forms. The RFC section appears to be missing lines between the RFC rows. I also see an outer border with gaps between the rows. I'd like it to see it with the same basic appearance as on the Grid forms since the table setup there seems to be easy to understand.

**Comment by pbowen-oc** [comment]
@MartijnR - We would rather have a link from the RFC field to its parent field than to show old/new values in the RFC area.

**Comment by pbowen-oc** [comment]
@MartijnR - We have a few minor change requests:
1. For the apply to all checkbox, please capitalize apply - "Apply to all"
2. For the apply to all text field, please change the help text in the empty field to "Enter a reason for your changes". For the individual field RFC text boxes, leave the help text as it is now.
3. For required RFC fields from repeating groups, please put the Required Asterisk after the row number. It is currently between the field label and the row number.

**Comment by MartijnR** [comment]
* [ ] in non-Grid theme, there is a space between the RFC fields that shouldn't be there
