### ISSUE TITLE
Maps not showing on Enketo

### ISSUE THREAD

**Issue by faith-mutua** [kobotoolbox/enketo-express#840]
Hi @MartijnR 

Geopoint questions do not have maps showing on Enketo as usual. The questions now have a textbox like the text questions. This seems to have been caused by an Enketo deployment that was done today which had a fix for the time format issue https://github.com/kobotoolbox/enketo-express/issues/834. You can reproduce this using [this form](https://stage.ona.io/qastuff/41757/234892) - [ enketo url](https://enketo-stage.ona.io/x/#Ypvp).

**Comment by MartijnR** [comment]
Hi Faith,

I think something went wrong when upgrading the server. Try uploading it to http://opendatakit.org/xiframe/ and clicking "Preview in Enketo". This is always the latest version of Enketo (it's kind of a honeypot for bugs because this server is not used for data collection). I see this: https://odk.enke.to/preview?form=http://23.21.114.69/xlsform/downloads/tmpuskmijl1/maps.xml (temporary link).

You can also always check https://enke.to/::widgets as that is the production that I'm running and usually has a very recent version.
