### ISSUE TITLE
Image-map doesn't update selected state if SVG contains colors

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#888]
Paul to send image + form

**Comment by MartijnR** [comment]
The image contains inline style attributes that get priority over CSS style rules

```xml
<path
   d="m 208.06814,141.36 c 2.164,3.727 -22.047,42.918 -27.331,44.971 -8.323,-5.094 -15.405,-6.957 -21.865,-10.187 0,-8.448 0.87,-15.778 -0.621,-17.268 -1.491,-1.49 -11.553,-28.449 -11.553,-34.909 0,-6.46 2.24,-36.156 4.824,-34.684 2.866,1.633 25.964,13.316 48.999,18.033 0.01,6.47 0.97,22.71 7.55,34.05 z"
   id="path10"
   style="fill:#bbd1e6;stroke:#000000" />
```

**Comment by jnm** [comment]
Hi @MartijnR, the fix for this seems to break the calculated style feature [(point #4)](https://github.com/kobotoolbox/enketo-image-customization-widget/blob/d09c1642cef2969b33bed6edf259b2eaee3ad7b9/README.md#image-customization-widget) of the image customization widget. Here's what it looked like with 1.55.9:
![1 55 9](https://user-images.githubusercontent.com/2085013/34695660-a98511ca-f499-11e7-82df-9bda62ec33c1.png)
Then, with 1.55.10:
![1 55 10](https://user-images.githubusercontent.com/2085013/34695669-accce5ba-f499-11e7-874c-6e6befac623c.png)

Here are the [XLSForm and SVG map](https://github.com/kobotoolbox/enketo-express/files/1613147/example.zip) used in this example.

**Comment by MartijnR** [comment]
Ah yes makes sense. Sorry about that.  It's fixed now in the latest enketo-image-customization-widget. 

This made me realize that an SVG image with inline `style` attributes will probably not work at all (and never has) for this customization widget.

**Comment by jnm** [comment]
Thanks for such a quick fix! 🤘
