### ISSUE TITLE
markdown formatting on labels for choices?

### ISSUE THREAD

**Issue by danbjoseph** [kobotoolbox/enketo-express#983]
@pierregrandidier noted in this ODK [forum post](https://forum.opendatakit.org/t/how-can-i-add-styling-like-font-color-italics-etc-to-my-forms/12542/6) that formatting on the labels for choices doesn't appear to work

![screen shot 2018-04-10 at 5 57 40 pm](https://user-images.githubusercontent.com/4806884/38585683-b3169866-3ce8-11e8-8ee3-b13f947736be.png)

**Comment by MartijnR** [comment]
Thanks!

It would be feasible for inline choice labels (i.e. in the XForm body), but not for all labels because Enketo doesn't do the markdown transformation on the client. It does this on the server (and external data is not known at that time, internal data may also present an issue). The negative performance impact of moving that transformation to the client would be significant. Will consider this further.

**Comment by enketo-issue-mover** [comment]
This issue was moved to enketo/enketo-core#554
